import ThemeRegistry from '@/libs/provider/ThemeRegistry';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import BasicPopover from '@/components/button/floating/Floating';
import './globals.css';

export const metadata = {
  title: 'Luis Felipe - Work Portfolio',
  name: 'Description',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ThemeRegistry options={{ key: 'mui', prepend: false }}>
          <header style={{ width: '100%' }}>
            <Header />
          </header>
          <main style={{ width: '100%' }}>{children}</main>
          <footer>
            <Footer />
          </footer>
          <BasicPopover />
        </ThemeRegistry>
      </body>
    </html>
  );
}
