import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import './globals.css';

export const metadata = {
  title: 'Luis Felipe - Work Portfolio',
  name: 'Description',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <header style={{ width: '100%' }}>
          <Header />
        </header>
        <main style={{ width: '100%' }}>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
